name: sd_playground
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - numpy=1.19.2
  - pip:
    - diffusers==0.2.4  # Will update as soon as the new version comes out! Until then you have to patch it! :')
    - transformers==4.19.2
    - scipy==1.9.1
    - matplotlib==3.5.3
    - fire==0.4.0
    - opencv-python==4.6.0.66
    - exif==1.3.5

